version: '3'
services:

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./front:/usr/src/app/
      - /usr/src/app/node_modules
    environment: 
      NODE_ENV: "developpement"
      BACK_URL: "http://localhost:1337"

volumes:
  persistent: