version: '3'
services:

  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    environment: 
      NODE_ENV: "production"

volumes:
  persistent: